/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModeloBeans.BeansAluno;
import ModeloBeans.BeansTabela;
import ModeloConection.ConexaoBD;
import ModeloDAO.DaoAluno;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Peterson Gomes
 */
public class FormAluno extends javax.swing.JFrame {

    ConexaoBD conection = new ConexaoBD();
    BeansAluno mod = new BeansAluno();
    DaoAluno daoAluno = new DaoAluno();
    int flag = 0;
    private String caminhoImagem = null;
    
   private byte[] foto = null;

    public byte[] getFoto() {
        return foto;
    }

    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
   
   

    public FormAluno() {
        initComponents();
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagem/setalogoClaro.png"));
        this.setIconImage(ico);
        preencherTabela("select *from alu order by nome_alu");
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPaneAbas = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEnderecoAlunos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNumeroAlunos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldComplementoAlunos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldBairroAlunos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCidadeAlunos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextFieldCepAlunos = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPaisAlunos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxUfAluno = new javax.swing.JComboBox<>();
        jButtonSalvarAlunos = new javax.swing.JButton();
        jButtonAlterarAlunos = new javax.swing.JButton();
        jButtonCancelarAlunos = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldNomeAlunos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldCpfAlunos = new javax.swing.JFormattedTextField();
        jComboBoxSexoAlunos = new javax.swing.JComboBox<>();
        jFormattedTextFieldNascAlunos = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldRgAluno = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldCodAluno = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldEscolaMatriculada = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldSerieCursandoAluno = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabelNomeResponsavel = new javax.swing.JLabel();
        jTextFieldNomeResponsavel = new javax.swing.JTextField();
        jLabelRgResponsavel = new javax.swing.JLabel();
        jFormattedTextFieldRgResponsavel = new javax.swing.JFormattedTextField();
        jLabel20CpfResponsavel = new javax.swing.JLabel();
        jFormattedTextFieldCpfResponsavel = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jFormattedTextFieldNascResponsavel = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBoxSexoResponsavel = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextFieldTelCasaAlunos = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextFieldTelCelAlunos = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jFormattedTextFieldTelRecadoResponsavel = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacaoAluno = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldPesquisarAluno = new javax.swing.JTextField();
        jButtonPesquisarAluno = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();
        jButtonNovoAluno = new javax.swing.JButton();
        jButtonExcluirFoto = new javax.swing.JButton();
        jLabeldaFoto = new javax.swing.JLabel();
        jButtonExcluirAluno = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Alunos e Responsáveis");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/ImagemTelaCadastroAluno.png"))); // NOI18N
        getContentPane().add(jLabel27);
        jLabel27.setBounds(280, 0, 102, 70);

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 3, 18)); // NOI18N
        jLabel1.setText("Cadastro de Aluno e Responsáveis");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 20, 350, 30);

        jTabbedPaneAbas.setBackground(new java.awt.Color(0, 0, 153));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Endereço :");

        jTextFieldEnderecoAlunos.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("N° :");

        jTextFieldNumeroAlunos.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Complemento :");

        jTextFieldComplementoAlunos.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Bairro :");

        jTextFieldBairroAlunos.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Cidade :");

        jTextFieldCidadeAlunos.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("CEP :");

        try {
            jFormattedTextFieldCepAlunos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCepAlunos.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("País :");

        jTextFieldPaisAlunos.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("UF:");

        jComboBoxUfAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RJ", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBoxUfAluno.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEnderecoAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumeroAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldComplementoAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBairroAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCidadeAlunos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxUfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCepAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jTextFieldPaisAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEnderecoAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNumeroAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldComplementoAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jFormattedTextFieldCepAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldBairroAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCidadeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldPaisAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxUfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButtonSalvarAlunos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSalvarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeSalvar.png"))); // NOI18N
        jButtonSalvarAlunos.setText("Salvar");
        jButtonSalvarAlunos.setEnabled(false);
        jButtonSalvarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAlunosActionPerformed(evt);
            }
        });

        jButtonAlterarAlunos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAlterarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeEdit.png"))); // NOI18N
        jButtonAlterarAlunos.setText("Alterar");
        jButtonAlterarAlunos.setEnabled(false);
        jButtonAlterarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarAlunosActionPerformed(evt);
            }
        });

        jButtonCancelarAlunos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCancelarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeCancelar.png"))); // NOI18N
        jButtonCancelarAlunos.setText("Cancelar");
        jButtonCancelarAlunos.setEnabled(false);
        jButtonCancelarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAlunosActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldNomeAlunos.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome :");

        try {
            jFormattedTextFieldCpfAlunos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpfAlunos.setEnabled(false);

        jComboBoxSexoAlunos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxSexoAlunos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Masculino", "Feminino" }));
        jComboBoxSexoAlunos.setEnabled(false);

        try {
            jFormattedTextFieldNascAlunos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNascAlunos.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Sexo :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CPF :");

        try {
            jFormattedTextFieldRgAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRgAluno.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("RG :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nascimento :");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("COD:");

        jTextFieldCodAluno.setEditable(false);
        jTextFieldCodAluno.setEnabled(false);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Escola Matriculada :");

        jTextFieldEscolaMatriculada.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Cursando :");

        jTextFieldSerieCursandoAluno.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEscolaMatriculada, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldRgAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCpfAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldNascAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSexoAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 22, Short.MAX_VALUE))
                            .addComponent(jTextFieldSerieCursandoAluno)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldCodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldRgAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldCpfAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldNascAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxSexoAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldEscolaMatriculada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldSerieCursandoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNomeResponsavel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNomeResponsavel.setText("Nome *");

        jTextFieldNomeResponsavel.setEnabled(false);

        jLabelRgResponsavel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRgResponsavel.setText("RG :");

        try {
            jFormattedTextFieldRgResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRgResponsavel.setEnabled(false);
        jFormattedTextFieldRgResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldRgResponsavelActionPerformed(evt);
            }
        });

        jLabel20CpfResponsavel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20CpfResponsavel.setText("CPF :");

        try {
            jFormattedTextFieldCpfResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpfResponsavel.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Nascimento :");

        try {
            jFormattedTextFieldNascResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNascResponsavel.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Sexo :");

        jComboBoxSexoResponsavel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxSexoResponsavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Masculino", "Feminino" }));
        jComboBoxSexoResponsavel.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Residencial :");

        try {
            jFormattedTextFieldTelCasaAlunos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelCasaAlunos.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText(" Celular :");

        try {
            jFormattedTextFieldTelCelAlunos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelCelAlunos.setEnabled(false);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Recado:");

        try {
            jFormattedTextFieldTelRecadoResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelRecadoResponsavel.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelNomeResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelRgResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldRgResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel20CpfResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCpfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldNascResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSexoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldTelCasaAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldTelCelAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldTelRecadoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeResponsavel)
                    .addComponent(jTextFieldNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldRgResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRgResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20CpfResponsavel)
                    .addComponent(jFormattedTextFieldCpfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jFormattedTextFieldNascResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBoxSexoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jFormattedTextFieldTelCasaAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jFormattedTextFieldTelCelAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jFormattedTextFieldTelRecadoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Responsavel :");

        jTextAreaObservacaoAluno.setColumns(20);
        jTextAreaObservacaoAluno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextAreaObservacaoAluno.setRows(5);
        jTextAreaObservacaoAluno.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaObservacaoAluno);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Observação :");

        jTextFieldPesquisarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarAlunoActionPerformed(evt);
            }
        });

        jButtonPesquisarAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPesquisarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconePesquisar.png"))); // NOI18N
        jButtonPesquisarAluno.setText("Pesquisar");
        jButtonPesquisarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarAlunoActionPerformed(evt);
            }
        });

        jTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlunoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAluno);

        jButtonNovoAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNovoAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeNovo.png"))); // NOI18N
        jButtonNovoAluno.setText("Novo");
        jButtonNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoAlunoActionPerformed(evt);
            }
        });

        jButtonExcluirFoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonExcluirFoto.setText("Excluir");
        jButtonExcluirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirFotoActionPerformed(evt);
            }
        });

        jLabeldaFoto.setBackground(new java.awt.Color(255, 255, 255));
        jLabeldaFoto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeldaFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeldaFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IMAGEMFOTO.png"))); // NOI18N
        jLabeldaFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabeldaFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeldaFotoMousePressed(evt);
            }
        });

        jButtonExcluirAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonExcluirAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeExcluir.png"))); // NOI18N
        jButtonExcluirAluno.setText("Excluir");
        jButtonExcluirAluno.setEnabled(false);
        jButtonExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButtonPesquisarAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPesquisarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabeldaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExcluirFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvarAlunos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelarAlunos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAlterarAlunos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluirAluno)
                        .addGap(195, 195, 195))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabeldaFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPesquisarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarAluno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarAlunos)
                    .addComponent(jButtonCancelarAlunos)
                    .addComponent(jButtonNovoAluno)
                    .addComponent(jButtonAlterarAlunos)
                    .addComponent(jButtonExcluirAluno))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPaneAbas.addTab("Alunos", jPanel3);

        getContentPane().add(jTabbedPaneAbas);
        jTabbedPaneAbas.setBounds(20, 50, 910, 660);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/imagem fundo cadastro usuario.jpg"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(-20, -10, 1170, 830);

        setSize(new java.awt.Dimension(955, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jButtonPesquisarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarAlunoActionPerformed
        mod.setPesquisar(jTextFieldPesquisarAluno.getText());// pesquisa pelo campo nome do aluno
        BeansAluno model = daoAluno.buscaAluno(mod);
        // tras do banco e coloca nos campos
        jTextFieldCodAluno.setText(String.valueOf(model.getCodAluno()));
        jTextFieldNomeAlunos.setText(model.getNome());
        jFormattedTextFieldRgAluno.setText(model.getRg());
        jFormattedTextFieldCpfAlunos.setText(model.getCpf());
        jFormattedTextFieldNascAlunos.setText(model.getNasc());
        jComboBoxSexoAlunos.setSelectedItem(model.getSexo());
        jTextFieldEscolaMatriculada.setText(model.getEsco_Matri());
        jTextFieldNomeResponsavel.setText(model.getNomeResp());
        jFormattedTextFieldRgResponsavel.setText(model.getRgResp());
        jFormattedTextFieldCpfResponsavel.setText(model.getCpfResp());
        jFormattedTextFieldNascResponsavel.setText(model.getNascResp());
        jComboBoxSexoResponsavel.setSelectedItem(model.getSexoResp());
        jFormattedTextFieldTelCasaAlunos.setText(model.getTelCasa());
        jFormattedTextFieldTelCelAlunos.setText(model.getTelCel());
        jFormattedTextFieldTelRecadoResponsavel.setText(model.getTelRec());
        jTextFieldEnderecoAlunos.setText(model.getEndereco());
        jTextFieldNumeroAlunos.setText(model.getNumero());
        jTextFieldComplementoAlunos.setText(model.getComplemento());
        jFormattedTextFieldCepAlunos.setText(model.getCep());
        jTextFieldBairroAlunos.setText(model.getBairro());
        jTextFieldCidadeAlunos.setText(model.getCidade());
        jComboBoxUfAluno.setSelectedItem(model.getUf());
        jTextFieldPaisAlunos.setText(model.getPais());
        jTextAreaObservacaoAluno.setText(model.getObservacao());
        jTextFieldSerieCursandoAluno.setText(model.getSerieCursando());
          ImageIcon imagem =  new ImageIcon(mod.getFoto());
            Image img = imagem.getImage();
            Image novaimg = img.getScaledInstance(140, 135,java.awt.Image.SCALE_SMOOTH);
	    ImageIcon icon = new ImageIcon(novaimg);
	   jLabeldaFoto.setIcon(icon); 
        preencherTabela("select * from aluno where lower (nome_alu) like lower('%" + mod.getPesquisar()+ "%')");
        jButtonNovoAluno.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarAlunoActionPerformed

    private void jTextFieldPesquisarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarAlunoActionPerformed

    private void jFormattedTextFieldRgResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRgResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldRgResponsavelActionPerformed

    private void jButtonExcluirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirFotoActionPerformed
            jLabeldaFoto.setIcon(null);
            jLabeldaFoto.setText("SEM FOTO");
            jButtonExcluirAluno.setVisible(false);

        /*// metodo para anexar foto
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        ImageIcon icon=new ImageIcon(filename);
        jLabeldaFoto.setIcon(icon);*/
    }//GEN-LAST:event_jButtonExcluirFotoActionPerformed
        
    public void FOT() {       
         File caminhoo = new File(jLabeldaFoto.getIcon().toString());
         //JOptionPane.showMessageDialog(rootPane, caminhoo);
         //String caminho = caminhoo.toString().substring(6).replaceAll("%20", " ");// usar no netbeans dessa forma 
                  String caminho = caminhoo.toString().substring(10).replaceAll("%20", " ");// usar no jar dessa forma 
          
         //System.out.println(caminho);
          JOptionPane.showMessageDialog(rootPane, caminhoo);
        try {
            BufferedImage imagemBuffer = ImageIO.read(new File(caminho));
             try (ByteArrayOutputStream bytesImg = new ByteArrayOutputStream()) {
                 ImageIO.write(imagemBuffer, "png", bytesImg);
                 bytesImg.flush();
                 foto = bytesImg.toByteArray();
             }
            System.out.println(caminho);
            JOptionPane.showMessageDialog(rootPane, caminho);
        }catch (IOException ex) {
            
        } 	 		
     }
    
    private void jButtonSalvarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAlunosActionPerformed
        // Tratando pra nao deixar salvar com campos em branco
        if (jTextFieldNomeAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo NOME para continuar");
            jTextFieldNomeAlunos.requestFocus();
        } else if (jFormattedTextFieldRgAluno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo RG para continuar");
            jFormattedTextFieldRgAluno.requestFocus();
        } else if (jFormattedTextFieldCpfAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CPF para continuar");
            jFormattedTextFieldCpfAlunos.requestFocus();
        } else if (jFormattedTextFieldNascAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo DATA DE NASCIMENTO para continuar");
            jFormattedTextFieldNascAlunos.requestFocus();
        } else if (jTextFieldEscolaMatriculada.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Escola Matriculada para continuar");
            jTextFieldEscolaMatriculada.requestFocus();
        } else if (jTextFieldSerieCursandoAluno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CURSANDO  para continuar");
            jTextFieldSerieCursandoAluno.requestFocus();    
        } else if (jTextFieldNomeResponsavel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha O NOME DO RESPONSAVEL  para continuar");
            jTextFieldNomeResponsavel.requestFocus();
        } else if (jFormattedTextFieldRgResponsavel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha O RG DO RESPONSAVEL para continuar");
            jFormattedTextFieldRgResponsavel.requestFocus();
        } else if (jFormattedTextFieldCpfResponsavel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CPF DO RESPONSAVEL para continuar");
            jFormattedTextFieldCpfResponsavel.requestFocus();
        } else if (jFormattedTextFieldNascResponsavel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo DATA DE NASCIMENTO DO RESPONSAVEL para continuar");
            jFormattedTextFieldNascResponsavel.requestFocus();
        } else if (jFormattedTextFieldTelCasaAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha O TELEFONE RESIDENCIAL para continuar");
            jFormattedTextFieldTelCasaAlunos.requestFocus();
        } else if (jFormattedTextFieldTelCelAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo TELEFONE CELULARA para continuar");
            jFormattedTextFieldTelCelAlunos.requestFocus();
        } else if (jFormattedTextFieldTelRecadoResponsavel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo TELEFONE RECADO para continuar");
            jFormattedTextFieldTelRecadoResponsavel.requestFocus();
        } else if (jTextFieldEnderecoAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo ENDEREÇO para continuar");
            jTextFieldEnderecoAlunos.requestFocus();
        } else if (jTextFieldNumeroAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo NUMERO para continuar");
            jTextFieldNumeroAlunos.requestFocus();
        } else if (jTextFieldComplementoAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo COMPLEMENTO  para continuar");
            jTextFieldComplementoAlunos.requestFocus();
        } else if (jFormattedTextFieldCepAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CEP  para continuar");
            jFormattedTextFieldCepAlunos.requestFocus();
        } else if (jTextFieldBairroAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo BAIRRO  para continuar");
            jTextFieldBairroAlunos.requestFocus();
        } else if (jTextFieldCidadeAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CIDADE  para continuar");
            jTextFieldCidadeAlunos.requestFocus();
        } else if (jTextFieldPaisAlunos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo PAÍS  para continuar");
            jTextFieldPaisAlunos.requestFocus();
        } else // Salvando no banco de dados pelo botão Salvar
         if (flag == 1) {
                mod.setNome(jTextFieldNomeAlunos.getText());
                mod.setRg(jFormattedTextFieldRgAluno.getText());
                mod.setCpf(jFormattedTextFieldCpfAlunos.getText());
                mod.setNasc(jFormattedTextFieldNascAlunos.getText());
                mod.setSexo((String) jComboBoxSexoAlunos.getSelectedItem());
                mod.setEsco_Matri(jTextFieldEscolaMatriculada.getText());
                mod.setNomeResp(jTextFieldNomeResponsavel.getText());
                mod.setRgResp(jFormattedTextFieldRgResponsavel.getText());
                mod.setCpfResp(jFormattedTextFieldCpfResponsavel.getText());
                mod.setNascResp(jFormattedTextFieldNascResponsavel.getText());
                mod.setSexoResp((String) jComboBoxSexoResponsavel.getSelectedItem());
                mod.setTelCasa(jFormattedTextFieldTelCasaAlunos.getText());
                mod.setTelCel(jFormattedTextFieldTelCelAlunos.getText());
                mod.setTelRec(jFormattedTextFieldTelRecadoResponsavel.getText());
                mod.setEndereco(jTextFieldEnderecoAlunos.getText());
                mod.setNumero(jTextFieldNumeroAlunos.getText());
                mod.setComplemento(jTextFieldComplementoAlunos.getText());
                mod.setCep(jFormattedTextFieldCepAlunos.getText());
                mod.setBairro(jTextFieldBairroAlunos.getText());
                mod.setCidade(jTextFieldCidadeAlunos.getText());
                mod.setUf((String) jComboBoxUfAluno.getSelectedItem());
                mod.setPais(jTextFieldPaisAlunos.getText());
                mod.setObservacao(jTextAreaObservacaoAluno.getText());
                 FOT();
                mod.setFoto(foto);
                mod.setSerieCursando(jTextFieldSerieCursandoAluno.getText());
               daoAluno.Salvar(mod);
               preencherTabela("select *from aluno order by nome_alu");  
                //Limpar os campos depois de salvo
                jTextFieldCodAluno.setText("");
                jTextFieldNomeAlunos.setText("");
                jFormattedTextFieldRgAluno.setText("");
                jFormattedTextFieldCpfAlunos.setText("");
                jFormattedTextFieldNascAlunos.setText("");
                jComboBoxSexoAlunos.setSelectedItem("Escolha");
                jTextFieldEscolaMatriculada.setText("");
                jTextFieldNomeResponsavel.setText("");
                jFormattedTextFieldRgResponsavel.setText("");
                jFormattedTextFieldCpfResponsavel.setText("");
                jFormattedTextFieldNascResponsavel.setText("");
                jComboBoxSexoResponsavel.setSelectedItem("Escolha");
                jFormattedTextFieldTelCasaAlunos.setText("");
                jFormattedTextFieldTelCelAlunos.setText("");
                jFormattedTextFieldTelRecadoResponsavel.setText("");
                jTextFieldEnderecoAlunos.setText("");
                jTextFieldNumeroAlunos.setText("");
                jTextFieldComplementoAlunos.setText("");
                jFormattedTextFieldCepAlunos.setText("");
                jTextFieldBairroAlunos.setText("");
                jTextFieldCidadeAlunos.setText("");
                jComboBoxUfAluno.setSelectedItem("Escolha");
                jTextFieldPaisAlunos.setText("");
                jTextAreaObservacaoAluno.setText("");
                jLabeldaFoto.setIcon(null);
                jTextFieldSerieCursandoAluno.setText("");
                //Bloqueando os campos novamente, o  simbolo ( ! ) significa ao contrario .       
                jTextFieldNomeAlunos.setEnabled(!true);
                jFormattedTextFieldRgAluno.setEnabled(!true);
                jFormattedTextFieldCpfAlunos.setEnabled(!true);
                jFormattedTextFieldNascAlunos.setEnabled(!true);
                jComboBoxSexoAlunos.setEnabled(!true);
                jTextFieldEscolaMatriculada.setEnabled(!true);
                jTextFieldNomeResponsavel.setEnabled(!true);
                jFormattedTextFieldRgResponsavel.setEnabled(!true);
                jFormattedTextFieldCpfResponsavel.setEnabled(!true);
                jFormattedTextFieldNascResponsavel.setEnabled(!true);
                jComboBoxSexoResponsavel.setEnabled(!true);
                jFormattedTextFieldTelCasaAlunos.setEnabled(!true);
                jFormattedTextFieldTelCelAlunos.setEnabled(!true);
                jFormattedTextFieldTelRecadoResponsavel.setEnabled(!true);
                jTextFieldEnderecoAlunos.setEnabled(!true);
                jTextFieldNumeroAlunos.setEnabled(!true);
                jTextFieldComplementoAlunos.setEnabled(!true);
                jFormattedTextFieldCepAlunos.setEnabled(!true);
                jTextFieldBairroAlunos.setEnabled(!true);
                jTextFieldCidadeAlunos.setEnabled(!true);
                jComboBoxUfAluno.setEnabled(!true);
                jTextFieldPaisAlunos.setEnabled(!true);
                jTextAreaObservacaoAluno.setEnabled(!true);
                jTextFieldSerieCursandoAluno.setEnabled(false);
                jButtonNovoAluno.setEnabled(true);
                jButtonCancelarAlunos.setEnabled(false);
                jButtonSalvarAlunos.setEnabled(false);
            } else {
                // Salvando no banco de dados pelo botão Salvar 
                mod.setCodAluno(Integer.parseInt(jTextFieldCodAluno.getText()));
                mod.setNome(jTextFieldNomeAlunos.getText());
                mod.setRg(jFormattedTextFieldRgAluno.getText());
                mod.setCpf(jFormattedTextFieldCpfAlunos.getText());
                mod.setNasc(jFormattedTextFieldNascAlunos.getText());
                mod.setSexo((String) jComboBoxSexoAlunos.getSelectedItem());
                mod.setEsco_Matri(jTextFieldEscolaMatriculada.getText());
                mod.setNomeResp(jTextFieldNomeResponsavel.getText());
                mod.setRgResp(jFormattedTextFieldRgResponsavel.getText());
                mod.setCpfResp(jFormattedTextFieldCpfResponsavel.getText());
                mod.setNascResp(jFormattedTextFieldNascResponsavel.getText());
                mod.setSexoResp((String) jComboBoxSexoResponsavel.getSelectedItem());
                mod.setTelCasa(jFormattedTextFieldTelCasaAlunos.getText());
                mod.setTelCel(jFormattedTextFieldTelCelAlunos.getText());
                mod.setTelRec(jFormattedTextFieldTelRecadoResponsavel.getText());
                mod.setEndereco(jTextFieldEnderecoAlunos.getText());
                mod.setNumero(jTextFieldNumeroAlunos.getText());
                mod.setComplemento(jTextFieldComplementoAlunos.getText());
                mod.setCep(jFormattedTextFieldCepAlunos.getText());
                mod.setBairro(jTextFieldBairroAlunos.getText());
                mod.setCidade(jTextFieldCidadeAlunos.getText());
                mod.setUf((String) jComboBoxUfAluno.getSelectedItem());
                mod.setPais(jTextFieldPaisAlunos.getText());
                mod.setObservacao(jTextAreaObservacaoAluno.getText());
                FOT();
                mod.setFoto(foto);
                mod.setSerieCursando(jTextFieldSerieCursandoAluno.getText());
               daoAluno.Editar(mod);
               preencherTabela("select *from aluno order by nome_alu"); 
               //Limpar os campos depois de salvo
                jTextFieldCodAluno.setText("");
                jTextFieldNomeAlunos.setText("");
                jFormattedTextFieldRgAluno.setText("");
                jFormattedTextFieldCpfAlunos.setText("");
                jFormattedTextFieldNascAlunos.setText("");
                jComboBoxSexoAlunos.setSelectedItem("");
                jTextFieldEscolaMatriculada.setText("");
                jTextFieldNomeResponsavel.setText("");
                jFormattedTextFieldRgResponsavel.setText("");
                jFormattedTextFieldCpfResponsavel.setText("");
                jFormattedTextFieldNascResponsavel.setText("");
                jComboBoxSexoResponsavel.setSelectedItem("");
                jFormattedTextFieldTelCasaAlunos.setText("");
                jFormattedTextFieldTelCelAlunos.setText("");
                jFormattedTextFieldTelRecadoResponsavel.setText("");
                jTextFieldEnderecoAlunos.setText("");
                jTextFieldNumeroAlunos.setText("");
                jTextFieldComplementoAlunos.setText("");
                jFormattedTextFieldCepAlunos.setText("");
                jTextFieldBairroAlunos.setText("");
                jTextFieldCidadeAlunos.setText("");
                jComboBoxUfAluno.setSelectedItem("");
                jTextFieldPaisAlunos.setText("");
                jTextAreaObservacaoAluno.setText("");
                //jLabeldaFoto.setIcon(null);
                jTextFieldSerieCursandoAluno.setText("");
                //Bloqueando os campos novamente, o  simbolo ( ! ) significa ao contrario .       
                jTextFieldNomeAlunos.setEnabled(!true);
                jFormattedTextFieldRgAluno.setEnabled(!true);
                jFormattedTextFieldCpfAlunos.setEnabled(!true);
                jFormattedTextFieldNascAlunos.setEnabled(!true);
                jComboBoxSexoAlunos.setEnabled(!true);
                jTextFieldEscolaMatriculada.setEnabled(!true);
                jTextFieldNomeResponsavel.setEnabled(!true);
                jFormattedTextFieldRgResponsavel.setEnabled(!true);
                jFormattedTextFieldCpfResponsavel.setEnabled(!true);
                jFormattedTextFieldNascResponsavel.setEnabled(!true);
                jComboBoxSexoResponsavel.setEnabled(!true);
                jFormattedTextFieldTelCasaAlunos.setEnabled(!true);
                jFormattedTextFieldTelCelAlunos.setEnabled(!true);
                jFormattedTextFieldTelRecadoResponsavel.setEnabled(!true);
                jTextFieldEnderecoAlunos.setEnabled(!true);
                jTextFieldNumeroAlunos.setEnabled(!true);
                jTextFieldComplementoAlunos.setEnabled(!true);
                jFormattedTextFieldCepAlunos.setEnabled(!true);
                jTextFieldBairroAlunos.setEnabled(!true);
                jTextFieldCidadeAlunos.setEnabled(!true);
                jComboBoxUfAluno.setEnabled(!true);
                jTextFieldPaisAlunos.setEnabled(!true);
                jTextAreaObservacaoAluno.setEnabled(!true);
                jTextFieldSerieCursandoAluno.setEnabled(false);
                jButtonNovoAluno.setEnabled(true);
                jButtonCancelarAlunos.setEnabled(false);
                jButtonSalvarAlunos.setEnabled(false);
         }
                            
       // int resposta = 0;
        //resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente salvar?\n Todos os campos obrigatorios estão preenchidos ? ");
        // jLabelFoto.setIcon(model.getfoto());
    }//GEN-LAST:event_jButtonSalvarAlunosActionPerformed

    private void jLabeldaFotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldaFotoMousePressed
          try {
            //Criação do FileChooser  
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("BR5");
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            
            if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                //aqui voce pega o arquivo que o usuario selecionou e joga dentro de uma variavel do tipo ImageIcon
                ImageIcon icone = new ImageIcon(fileChooser.getSelectedFile().toString());  
           
                File file = new File(icone.toString());
                  FileInputStream fi = new FileInputStream(file);
                  //Converte a imagem em binário
			long fileSize = file.length(); 
                  	           foto = new byte[(int)fileSize];
                                            
			           fi.read(foto);
			           ImageIcon imagem = new ImageIcon(foto);
                jLabeldaFoto.setText("");
                jLabeldaFoto.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(115, 120, Image.SCALE_SMOOTH)));
                jLabeldaFoto.setVisible(true);
            } 
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não foi possivel carregar a imagem.\n"+erro.toString());
        }
                                                              
    }//GEN-LAST:event_jLabeldaFotoMousePressed

    private void jButtonExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirAlunoActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente exluir ?");// abre uma caixa pra pergunta se é verdadeiro ou falso .
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setCodAluno(Integer.parseInt(jTextFieldCodAluno.getText()));
            daoAluno.Excluir(mod);
           
                        //limpa os campos 
                jTextFieldCodAluno.setText("");
                jTextFieldNomeAlunos.setText("");
                jFormattedTextFieldRgAluno.setText("");
                jFormattedTextFieldCpfAlunos.setText("");
                jFormattedTextFieldNascAlunos.setText("");
                jComboBoxSexoAlunos.setSelectedItem("Escolha");
                jTextFieldEscolaMatriculada.setText("");
                jTextFieldNomeResponsavel.setText("");
                jFormattedTextFieldRgResponsavel.setText("");
                jFormattedTextFieldCpfResponsavel.setText("");
                jFormattedTextFieldNascResponsavel.setText("");
                jComboBoxSexoResponsavel.setSelectedItem("Escolha");
                jFormattedTextFieldTelCasaAlunos.setText("");
                jFormattedTextFieldTelCelAlunos.setText("");
                jFormattedTextFieldTelRecadoResponsavel.setText("");
                jTextFieldEnderecoAlunos.setText("");
                jTextFieldNumeroAlunos.setText("");
                jTextFieldComplementoAlunos.setText("");
                jFormattedTextFieldCepAlunos.setText("");
                jTextFieldBairroAlunos.setText("");
                jTextFieldCidadeAlunos.setText("");
                jComboBoxUfAluno.setSelectedItem("Escolha");
                jTextFieldPaisAlunos.setText("");
                jTextAreaObservacaoAluno.setText("");
                jTextFieldSerieCursandoAluno.setText("");
               // jLabeldaFoto.setIcon(null);
                  //Desabilitando e abilitando os botoes
                jButtonAlterarAlunos.setEnabled(false);
                jButtonCancelarAlunos.setEnabled(false);
                jButtonNovoAluno.setEnabled(true);
                jButtonExcluirAluno.setEnabled(false);
               preencherTabela("select *from aluno order by nome_alu");
        }
    }//GEN-LAST:event_jButtonExcluirAlunoActionPerformed

    private void jButtonCancelarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAlunosActionPerformed
        jTextFieldNomeAlunos.setEnabled(!true);
        jFormattedTextFieldRgAluno.setEnabled(!true);
        jFormattedTextFieldCpfAlunos.setEnabled(!true);
        jFormattedTextFieldNascAlunos.setEnabled(!true);
        jComboBoxSexoAlunos.setEnabled(!true);
        jTextFieldEscolaMatriculada.setEnabled(!true);
        jTextFieldNomeResponsavel.setEnabled(!true);
        jFormattedTextFieldRgResponsavel.setEnabled(!true);
        jFormattedTextFieldCpfResponsavel.setEnabled(!true);
        jFormattedTextFieldNascResponsavel.setEnabled(!true);
        jComboBoxSexoResponsavel.setEnabled(!true);
        jFormattedTextFieldTelCasaAlunos.setEnabled(!true);
        jFormattedTextFieldTelCelAlunos.setEnabled(!true);
        jFormattedTextFieldTelRecadoResponsavel.setEnabled(!true);
        jTextFieldEnderecoAlunos.setEnabled(!true);
        jTextFieldNumeroAlunos.setEnabled(!true);
        jTextFieldComplementoAlunos.setEnabled(!true);
        jFormattedTextFieldCepAlunos.setEnabled(!true);
        jTextFieldBairroAlunos.setEnabled(!true);
        jTextFieldCidadeAlunos.setEnabled(!true);
        jComboBoxUfAluno.setEnabled(!true);
        jTextFieldPaisAlunos.setEnabled(!true);
        jTextAreaObservacaoAluno.setEnabled(!true);
        jTextFieldSerieCursandoAluno.setEnabled(false);
        jButtonCancelarAlunos.setEnabled(!true);
        jButtonSalvarAlunos.setEnabled(!true);
        jTextFieldPesquisarAluno.setEnabled(!false);
        jButtonPesquisarAluno.setEnabled(!false);
        jButtonNovoAluno.setEnabled(true);
        jButtonExcluirAluno.setEnabled(false);
        jButtonAlterarAlunos.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarAlunosActionPerformed

    private void jButtonNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoAlunoActionPerformed
        flag = 1;
        // AO CLICAR NO NOVO LIBERA OS CAMPOS 
        jTextFieldNomeAlunos.setEnabled(true);
        jFormattedTextFieldRgAluno.setEnabled(true);
        jFormattedTextFieldCpfAlunos.setEnabled(true);
        jFormattedTextFieldNascAlunos.setEnabled(true);
        jComboBoxSexoAlunos.setEnabled(true);
        jTextFieldEscolaMatriculada.setEnabled(true);
        jTextFieldNomeResponsavel.setEnabled(true);
        jFormattedTextFieldRgResponsavel.setEnabled(true);
        jFormattedTextFieldCpfResponsavel.setEnabled(true);
        jFormattedTextFieldNascResponsavel.setEnabled(true);
        jComboBoxSexoResponsavel.setEnabled(true);
        jFormattedTextFieldTelCasaAlunos.setEnabled(true);
        jFormattedTextFieldTelCelAlunos.setEnabled(true);
        jFormattedTextFieldTelRecadoResponsavel.setEnabled(true);
        jTextFieldEnderecoAlunos.setEnabled(true);
        jTextFieldNumeroAlunos.setEnabled(true);
        jTextFieldComplementoAlunos.setEnabled(true);
        jFormattedTextFieldCepAlunos.setEnabled(true);
        jTextFieldBairroAlunos.setEnabled(true);
        jTextFieldCidadeAlunos.setEnabled(true);
        jComboBoxUfAluno.setEnabled(true);
        jTextFieldPaisAlunos.setEnabled(true);
        jTextAreaObservacaoAluno.setEnabled(true);
        jTextFieldSerieCursandoAluno.setEnabled(true);
        jButtonCancelarAlunos.setEnabled(true);
        jButtonSalvarAlunos.setEnabled(true);
        jTextFieldPesquisarAluno.setEnabled(false);
        jButtonPesquisarAluno.setEnabled(false);
        jButtonNovoAluno.setEnabled(false);
                 //Limpar os campos depois de salvo
                jTextFieldCodAluno.setText("");
                jTextFieldNomeAlunos.setText("");
                jFormattedTextFieldRgAluno.setText("");
                jFormattedTextFieldCpfAlunos.setText("");
                jFormattedTextFieldNascAlunos.setText("");
                jComboBoxSexoAlunos.setSelectedItem("Escolha");
                jTextFieldEscolaMatriculada.setText("");
                jTextFieldNomeResponsavel.setText("");
                jFormattedTextFieldRgResponsavel.setText("");
                jFormattedTextFieldCpfResponsavel.setText("");
                jFormattedTextFieldNascResponsavel.setText("");
                jComboBoxSexoResponsavel.setSelectedItem("Escolha");
                jFormattedTextFieldTelCasaAlunos.setText("");
                jFormattedTextFieldTelCelAlunos.setText("");
                jFormattedTextFieldTelRecadoResponsavel.setText("");
                jTextFieldEnderecoAlunos.setText("");
                jTextFieldNumeroAlunos.setText("");
                jTextFieldComplementoAlunos.setText("");
                jFormattedTextFieldCepAlunos.setText("");
                jTextFieldBairroAlunos.setText("");
                jTextFieldCidadeAlunos.setText("");
                jComboBoxUfAluno.setSelectedItem("Escolha");
                jTextFieldPaisAlunos.setText("");
                jTextAreaObservacaoAluno.setText("");
                //jLabeldaFoto.setIcon(null);
                jTextFieldSerieCursandoAluno.setText("");
                

    }//GEN-LAST:event_jButtonNovoAlunoActionPerformed
  
    private void jButtonAlterarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarAlunosActionPerformed
        flag = 2;
        jTextFieldNomeAlunos.setEnabled(true);
        jFormattedTextFieldRgAluno.setEnabled(true);
        jFormattedTextFieldCpfAlunos.setEnabled(true);
        jFormattedTextFieldNascAlunos.setEnabled(true);
        jComboBoxSexoAlunos.setEnabled(true);
        jTextFieldEscolaMatriculada.setEnabled(true);
        jTextFieldNomeResponsavel.setEnabled(true);
        jFormattedTextFieldRgResponsavel.setEnabled(true);
        jFormattedTextFieldCpfResponsavel.setEnabled(true);
        jFormattedTextFieldNascResponsavel.setEnabled(true);
        jComboBoxSexoResponsavel.setEnabled(true);
        jFormattedTextFieldTelCasaAlunos.setEnabled(true);
        jFormattedTextFieldTelCelAlunos.setEnabled(true);
        jFormattedTextFieldTelRecadoResponsavel.setEnabled(true);
        jTextFieldEnderecoAlunos.setEnabled(true);
        jTextFieldNumeroAlunos.setEnabled(true);
        jTextFieldComplementoAlunos.setEnabled(true);
        jFormattedTextFieldCepAlunos.setEnabled(true);
        jTextFieldBairroAlunos.setEnabled(true);
        jTextFieldCidadeAlunos.setEnabled(true);
        jComboBoxUfAluno.setEnabled(true);
        jTextFieldPaisAlunos.setEnabled(true);
        jTextAreaObservacaoAluno.setEnabled(true);
        jTextFieldSerieCursandoAluno.setEnabled(true);
        jButtonSalvarAlunos.setEnabled(true);
        jButtonExcluirAluno.setEnabled(false);
        jButtonAlterarAlunos.setEnabled(false);
        
        
        
       
    }//GEN-LAST:event_jButtonAlterarAlunosActionPerformed

    private void jTableAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlunoMouseClicked
        //Mouse clicked , ao clicar no nome da tabela ao preenche os campos .
        String nome_usuario = "" + jTableAluno.getValueAt(jTableAluno.getSelectedRow(), 1);
        conection.conexao();
        conection.executaSql("select * from aluno where nome_alu ='" + nome_usuario + "'");
        try {
           conection.rs.first();
           jTextFieldCodAluno.setText(String.valueOf(conection.rs.getInt("id_alu")));
           jTextFieldNomeAlunos.setText(conection.rs.getString("nome_alu"));
           jFormattedTextFieldRgAluno.setText(conection.rs.getString("rg_alu"));
           jFormattedTextFieldCpfAlunos.setText(conection.rs.getString("cpf_alu"));
           jFormattedTextFieldNascAlunos.setText(conection.rs.getString("nasc_alu"));
           jComboBoxSexoAlunos.setSelectedItem(conection.rs.getString("sexo_alu"));
           jTextFieldEscolaMatriculada.setText(conection.rs.getString("esc_alu"));
           jTextFieldNomeResponsavel.setText(conection.rs.getString("resp_nome_alu"));
           jFormattedTextFieldRgResponsavel.setText(conection.rs.getString("resp_rg_alu"));
           jFormattedTextFieldCpfResponsavel.setText(conection.rs.getString("resp_cpf_alu"));
           jFormattedTextFieldNascResponsavel.setText(conection.rs.getString("resp_nasc_alu"));
           jComboBoxSexoResponsavel.setSelectedItem(conection.rs.getString("resp_sexo_alu"));
           jFormattedTextFieldTelCasaAlunos.setText(conection.rs.getString("tel_alu"));
           jFormattedTextFieldTelCelAlunos.setText(conection.rs.getString("cel01_alu"));
           jFormattedTextFieldTelRecadoResponsavel.setText(conection.rs.getString("tel_rec_alu"));
           jTextFieldEnderecoAlunos.setText(conection.rs.getString("end_alu"));
           jTextFieldNumeroAlunos.setText(conection.rs.getString("num_alu"));
           jTextFieldComplementoAlunos.setText(conection.rs.getString("comple_alu"));
           jFormattedTextFieldCepAlunos.setText(conection.rs.getString("bairro_alu"));
           jTextFieldBairroAlunos.setText(conection.rs.getString("cid_alu"));
           jTextFieldCidadeAlunos.setText(conection.rs.getString("uf_alu"));
           jComboBoxUfAluno.setSelectedItem(conection.rs.getString("cep_alu"));
           jTextFieldPaisAlunos.setText(conection.rs.getString("pais_alu"));
           jTextAreaObservacaoAluno.setText(conection.rs.getString("obs_alu"));
           jLabeldaFoto.setText("");
           setFoto(conection.rs.getBytes("foto"));   //jLabeldaFoto.setIcon(conection.rs.getByte("foto"));
           ImageIcon imagem =  new ImageIcon(getFoto());// getFoto esta vindo null
             Image img = imagem.getImage();
             Image novaimg = img.getScaledInstance(140, 135,java.awt.Image.SCALE_SMOOTH);
	     ImageIcon icon = new ImageIcon(novaimg);
	   jLabeldaFoto.setIcon(icon); 
           jTextFieldSerieCursandoAluno.setText(conection.rs.getString("serie_alu"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar o Aluno/n");
        }
        conection.desconecta();
        jButtonNovoAluno.setEnabled(false);
        jButtonAlterarAlunos.setEnabled(true);
        jButtonExcluirAluno.setEnabled(true);
        jButtonCancelarAlunos.setEnabled(true);
        jButtonSalvarAlunos.setEnabled(false);
        jTextFieldNomeAlunos.setEnabled(!true);
                       // Bloquear os campos
                jFormattedTextFieldRgAluno.setEnabled(!true);
                jFormattedTextFieldCpfAlunos.setEnabled(!true);
                jFormattedTextFieldNascAlunos.setEnabled(!true);
                jComboBoxSexoAlunos.setEnabled(!true);
                jTextFieldEscolaMatriculada.setEnabled(!true);
                jTextFieldNomeResponsavel.setEnabled(!true);
                jFormattedTextFieldRgResponsavel.setEnabled(!true);
                jFormattedTextFieldCpfResponsavel.setEnabled(!true);
                jFormattedTextFieldNascResponsavel.setEnabled(!true);
                jComboBoxSexoResponsavel.setEnabled(!true);
                jFormattedTextFieldTelCasaAlunos.setEnabled(!true);
                jFormattedTextFieldTelCelAlunos.setEnabled(!true);
                jFormattedTextFieldTelRecadoResponsavel.setEnabled(!true);
                jTextFieldEnderecoAlunos.setEnabled(!true);
                jTextFieldNumeroAlunos.setEnabled(!true);
                jTextFieldComplementoAlunos.setEnabled(!true);
                jFormattedTextFieldCepAlunos.setEnabled(!true);
                jTextFieldBairroAlunos.setEnabled(!true);
                jTextFieldCidadeAlunos.setEnabled(!true);
                jComboBoxUfAluno.setEnabled(!true);
                jTextFieldPaisAlunos.setEnabled(!true);
                jTextAreaObservacaoAluno.setEnabled(!true);
                jTextFieldSerieCursandoAluno.setEnabled(!true);
               
    }//GEN-LAST:event_jTableAlunoMouseClicked
 //Preenchendo a tabela 
    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();

        String[] colunas = new String[]{"COD", "Nome Aluno", "Escola Cadastrada","Cursando"};
        conection.conexao();
        conection.executaSql(sql);
        try {
            conection.rs.first();
            do {
                 dados.add(new Object[]{conection.rs.getInt("id_alu"), conection.rs.getString("nome_alu"), conection.rs.getString("esc_alu"),conection.rs.getString("serie_alu")});
            } while (conection.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Busque por outro Aluno para preencher a tabela"+ex);
        }
        BeansTabela modelo = new BeansTabela(dados, colunas);
        jTableAluno.setModel(modelo);
        jTableAluno.getColumnModel().getColumn(0).setPreferredWidth(40);// muda tamanho da linha na tabela 
        jTableAluno.getColumnModel().getColumn(0).setResizable(false);//Nao deixa o usuario mexe o tamanho da coluna
        jTableAluno.getColumnModel().getColumn(1).setPreferredWidth(200);// muda tamanho da linha na tabela 
        jTableAluno.getColumnModel().getColumn(1).setResizable(false);//Nao deixa o usuario mexe o tamanho da coluna
        jTableAluno.getColumnModel().getColumn(2).setPreferredWidth(200);// muda tamanho da linha na tabela 
        jTableAluno.getColumnModel().getColumn(2).setResizable(false);//Nao deixa o usuario mexe o tamanho da coluna
        jTableAluno.getColumnModel().getColumn(3).setPreferredWidth(100);// muda tamanho da linha na tabela 
        jTableAluno.getColumnModel().getColumn(3).setResizable(false);//Nao deixa o usuario mexe o tamanho da coluna
        jTableAluno.getTableHeader().setReorderingAllowed(false); // muda tamanho da linha na tabela */
        jTableAluno.setAutoResizeMode(jTableAluno.AUTO_RESIZE_OFF);//Tabela nao podera ser remimensionada
        jTableAluno.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conection.desconecta();

    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarAlunos;
    private javax.swing.JButton jButtonCancelarAlunos;
    private javax.swing.JButton jButtonExcluirAluno;
    private javax.swing.JButton jButtonExcluirFoto;
    private javax.swing.JButton jButtonNovoAluno;
    private javax.swing.JButton jButtonPesquisarAluno;
    private javax.swing.JButton jButtonSalvarAlunos;
    private javax.swing.JComboBox<String> jComboBoxSexoAlunos;
    private javax.swing.JComboBox<String> jComboBoxSexoResponsavel;
    private javax.swing.JComboBox<String> jComboBoxUfAluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldCepAlunos;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfAlunos;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfResponsavel;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascAlunos;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascResponsavel;
    private javax.swing.JFormattedTextField jFormattedTextFieldRgAluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldRgResponsavel;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelCasaAlunos;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelCelAlunos;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelRecadoResponsavel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel20CpfResponsavel;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNomeResponsavel;
    private javax.swing.JLabel jLabelRgResponsavel;
    private javax.swing.JLabel jLabeldaFoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneAbas;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JTextArea jTextAreaObservacaoAluno;
    private javax.swing.JTextField jTextFieldBairroAlunos;
    private javax.swing.JTextField jTextFieldCidadeAlunos;
    private javax.swing.JTextField jTextFieldCodAluno;
    private javax.swing.JTextField jTextFieldComplementoAlunos;
    private javax.swing.JTextField jTextFieldEnderecoAlunos;
    private javax.swing.JTextField jTextFieldEscolaMatriculada;
    private javax.swing.JTextField jTextFieldNomeAlunos;
    private javax.swing.JTextField jTextFieldNomeResponsavel;
    private javax.swing.JTextField jTextFieldNumeroAlunos;
    private javax.swing.JTextField jTextFieldPaisAlunos;
    private javax.swing.JTextField jTextFieldPesquisarAluno;
    private javax.swing.JTextField jTextFieldSerieCursandoAluno;
    // End of variables declaration//GEN-END:variables
}
