/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModeloBeans.BeansCondutor;
import ModeloConection.ConexaoBD;
import ModeloDAO.DaoCondutor;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Peterson Gomes
 */
public class FormCondutor extends javax.swing.JFrame {

    ConexaoBD conection = new ConexaoBD();
    BeansCondutor mod = new BeansCondutor();
    DaoCondutor DaoCondutor = new DaoCondutor();

    public FormCondutor() {
        initComponents();
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagem/setalogoClaro.png"));
        this.setIconImage(ico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneAbas = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEnderecoCondutor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNumeroCondutor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldComplementoCondutor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldBairroCondutor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCidadeCondutor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextFieldCepCondutor = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldUfCondutor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPaisCondutor = new javax.swing.JTextField();
        jTextFieldPesquisarCondutor = new javax.swing.JTextField();
        jButtonPesquisarCondutor = new javax.swing.JButton();
        jButtonNovoCondutor = new javax.swing.JButton();
        jButtonSalvarCondutor = new javax.swing.JButton();
        jButtonEditarCondutor = new javax.swing.JButton();
        jButtonCancelarCondutor = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldNomeCondutor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldCpfCondutor = new javax.swing.JFormattedTextField();
        jComboBoxSexoCondutor = new javax.swing.JComboBox<>();
        jFormattedTextFieldNascCondutor = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldRgCondutor = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldCnhCondutor = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jFormattedTextFieldEmissaoCondutor = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        jFormattedTextFieldValidadeCondutor = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldCategoriaCondutor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCivilCondutor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldCodCondutor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCondutor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextFieldTelefone01Condutor = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextFieldTelCelCondutor = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        jFormattedTextFieldTelefoneCondutor02 = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jButtonExcluirCondutor = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jTabbedPaneAbas.setEnabled(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Endereço :");

        jTextFieldEnderecoCondutor.setEnabled(false);

        jLabel8.setText("N° :");

        jTextFieldNumeroCondutor.setEnabled(false);

        jLabel9.setText("Complemento :");

        jTextFieldComplementoCondutor.setEnabled(false);

        jLabel10.setText("Bairro :");

        jTextFieldBairroCondutor.setEnabled(false);

        jLabel11.setText("Cidade :");

        jTextFieldCidadeCondutor.setEnabled(false);

        jLabel12.setText("CEP :");

        try {
            jFormattedTextFieldCepCondutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCepCondutor.setEnabled(false);
        jFormattedTextFieldCepCondutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCepCondutorActionPerformed(evt);
            }
        });

        jLabel13.setText("UF:");

        jTextFieldUfCondutor.setEnabled(false);

        jLabel14.setText("País :");

        jTextFieldPaisCondutor.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBairroCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCepCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPaisCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jTextFieldCidadeCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldUfCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEnderecoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumeroCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldComplementoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEnderecoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNumeroCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldComplementoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldBairroCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCidadeCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldUfCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jFormattedTextFieldCepCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldPaisCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTextFieldPesquisarCondutor.setEnabled(false);

        jButtonPesquisarCondutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconePesquisar.png"))); // NOI18N
        jButtonPesquisarCondutor.setText("Pesquisar");
        jButtonPesquisarCondutor.setEnabled(false);
        jButtonPesquisarCondutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCondutorActionPerformed(evt);
            }
        });

        jButtonNovoCondutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeNovo.png"))); // NOI18N
        jButtonNovoCondutor.setText("Novo");
        jButtonNovoCondutor.setEnabled(false);
        jButtonNovoCondutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCondutorActionPerformed(evt);
            }
        });

        jButtonSalvarCondutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeSalvar.png"))); // NOI18N
        jButtonSalvarCondutor.setText("Salvar");
        jButtonSalvarCondutor.setEnabled(false);
        jButtonSalvarCondutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCondutorActionPerformed(evt);
            }
        });

        jButtonEditarCondutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeEdit.png"))); // NOI18N
        jButtonEditarCondutor.setText("Editar");
        jButtonEditarCondutor.setEnabled(false);

        jButtonCancelarCondutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeCancelar.png"))); // NOI18N
        jButtonCancelarCondutor.setText("Cancelar");
        jButtonCancelarCondutor.setEnabled(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldNomeCondutor.setEnabled(false);

        jLabel2.setText("Nome :");

        try {
            jFormattedTextFieldCpfCondutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpfCondutor.setEnabled(false);

        jComboBoxSexoCondutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Masculino", "Feminino" }));
        jComboBoxSexoCondutor.setEnabled(false);

        try {
            jFormattedTextFieldNascCondutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNascCondutor.setEnabled(false);

        jLabel7.setText("Sexo :");

        jLabel4.setText("CPF :");

        try {
            jFormattedTextFieldRgCondutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRgCondutor.setEnabled(false);

        jLabel3.setText("RG :");

        jLabel6.setText("Nascimento :");

        jLabel1.setText("CNH :");

        try {
            jFormattedTextFieldCnhCondutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCnhCondutor.setEnabled(false);

        jLabel20.setText("Data de Emissão CNH:");

        try {
            jFormattedTextFieldEmissaoCondutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldEmissaoCondutor.setEnabled(false);

        jLabel27.setText("Validade CNH :");

        try {
            jFormattedTextFieldValidadeCondutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldValidadeCondutor.setEnabled(false);

        jLabel28.setText("Categoria Habilitação :");

        jTextFieldCategoriaCondutor.setEnabled(false);

        jLabel15.setText("Estado Civil :");

        jTextFieldCivilCondutor.setEnabled(false);

        jLabel22.setText("COD:");

        jTextFieldCodCondutor.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldNascCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSexoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCivilCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCategoriaCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNomeCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCodCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldRgCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCpfCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCnhCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldEmissaoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldValidadeCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldCodCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldRgCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCpfCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldCnhCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jFormattedTextFieldEmissaoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jFormattedTextFieldValidadeCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldNascCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxSexoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldCategoriaCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCivilCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jTableCondutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableCondutor);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Residencial :");

        try {
            jFormattedTextFieldTelefone01Condutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone01Condutor.setEnabled(false);

        jLabel17.setText(" Celular :");

        try {
            jFormattedTextFieldTelCelCondutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelCelCondutor.setEnabled(false);

        jLabel30.setText(" Celular 2 :");

        try {
            jFormattedTextFieldTelefoneCondutor02.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefoneCondutor02.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldTelefone01Condutor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldTelCelCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldTelefoneCondutor02, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jFormattedTextFieldTelefone01Condutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jFormattedTextFieldTelCelCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jFormattedTextFieldTelefoneCondutor02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel23.setText("Telefones:");

        jButtonExcluirCondutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/IconeExcluir.png"))); // NOI18N
        jButtonExcluirCondutor.setText("Excluir");
        jButtonExcluirCondutor.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisarCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisarCondutor))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jButtonNovoCondutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvarCondutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditarCondutor)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonExcluirCondutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelarCondutor)))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisarCondutor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextFieldPesquisarCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoCondutor)
                    .addComponent(jButtonSalvarCondutor)
                    .addComponent(jButtonEditarCondutor)
                    .addComponent(jButtonCancelarCondutor)
                    .addComponent(jButtonExcluirCondutor))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPaneAbas.addTab("Condutor", jPanel3);

        getContentPane().add(jTabbedPaneAbas);
        jTabbedPaneAbas.setBounds(40, 20, 960, 700);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/ImagemTelaCondutor.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(350, 0, 50, 40);

        jLabel18.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 3, 18)); // NOI18N
        jLabel18.setText("Cadastro de Condutores:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(410, 10, 230, 23);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/imagem fundo cadastro usuario.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(-70, -20, 1160, 810);

        setSize(new java.awt.Dimension(1054, 793));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldCepCondutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCepCondutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCepCondutorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //JOptionPane.showMessageDialog(rootPane, "Todos os campos são obrigatorio os preenchimentos ");//Mensagem sera exibida quando chamar a tela .
    }//GEN-LAST:event_formWindowOpened

    private void jButtonSalvarCondutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCondutorActionPerformed
        // Salvando no banco de dados pelo botão Salvar 
        mod.setNome(jTextFieldNomeCondutor.getText());
        mod.setRg(jFormattedTextFieldRgCondutor.getText());
        mod.setCnh(jFormattedTextFieldCnhCondutor.getText());
        mod.setEmissaoCnh(jFormattedTextFieldEmissaoCondutor.getText());
        mod.setValidadeCnh(jFormattedTextFieldValidadeCondutor.getText());
        mod.setNascimento(jFormattedTextFieldNascCondutor.getText());
        mod.setCivil(jTextFieldCivilCondutor.getText());
        mod.setCatHabilitacao(jTextFieldCategoriaCondutor.getText());
        mod.setTelefone01(jFormattedTextFieldTelefone01Condutor.getText());
        mod.setCelular(jFormattedTextFieldTelCelCondutor.getText());
        mod.setTelefone02(jFormattedTextFieldTelefoneCondutor02.getText());
        mod.setEndereço(jTextFieldEnderecoCondutor.getText());
        mod.setNumero(jTextFieldNumeroCondutor.getText());
        mod.setComplemento(jTextFieldComplementoCondutor.getText());
        mod.setBairro(jTextFieldBairroCondutor.getText());
        mod.setCidade(jTextFieldCidadeCondutor.getText());
        mod.setUf(jTextFieldUfCondutor.getText());
        mod.setCep(jFormattedTextFieldCepCondutor.getText());
        mod.setPais(jTextFieldPaisCondutor.getText());
        mod.setSexo((String) jComboBoxSexoCondutor.getSelectedItem());
        mod.setCpf(jFormattedTextFieldCpfCondutor.getText());
        DaoCondutor.Salvar(mod);

        
         // Ao salvar no banco de dados , limpa os campos para nova digitação 
         
        jTextFieldNomeCondutor.setText("");
        jFormattedTextFieldRgCondutor.setText("");
        jFormattedTextFieldCnhCondutor.setText("");
        jFormattedTextFieldEmissaoCondutor.setText("");
        jFormattedTextFieldValidadeCondutor.setText("");
        jFormattedTextFieldNascCondutor.setText("");
        jTextFieldCivilCondutor.setText("");
        jTextFieldCategoriaCondutor.setText("");
        jFormattedTextFieldTelefone01Condutor.setText("");
        jFormattedTextFieldTelCelCondutor.setText("");
        jFormattedTextFieldTelefoneCondutor02.setText("");
        jTextFieldEnderecoCondutor.setText("");
        jTextFieldNumeroCondutor.setText("");
        jTextFieldComplementoCondutor.setText("");
        jTextFieldBairroCondutor.setText("");
        jTextFieldCidadeCondutor.setText("");
        jTextFieldUfCondutor.setText("");
        jFormattedTextFieldCepCondutor.setText("");
        jTextFieldPaisCondutor.setText("");
        jFormattedTextFieldCpfCondutor.setText("");
        
        
        //Bloqueando os campos novamente, o  simbolo ( ! ) significa ao contrario .
        jTextFieldNomeCondutor.setEnabled(!true);
        jFormattedTextFieldRgCondutor.setEnabled(!true);
        jFormattedTextFieldCnhCondutor.setEnabled(!true);
        jFormattedTextFieldEmissaoCondutor.setEnabled(!true);
        jFormattedTextFieldValidadeCondutor.setEnabled(!true);
        jFormattedTextFieldNascCondutor.setEnabled(!true);
        jTextFieldCivilCondutor.setEnabled(!true);
        jTextFieldCategoriaCondutor.setEnabled(!true);
        jFormattedTextFieldTelefone01Condutor.setEnabled(!true);
        jFormattedTextFieldTelCelCondutor.setEnabled(!true);
        jFormattedTextFieldTelefoneCondutor02.setEnabled(!true);
        jTextFieldEnderecoCondutor.setEnabled(!true);
        jTextFieldNumeroCondutor.setEnabled(!true);
        jTextFieldComplementoCondutor.setEnabled(!true);
        jTextFieldBairroCondutor.setEnabled(!true);
        jTextFieldCidadeCondutor.setEnabled(!true);
        jTextFieldUfCondutor.setEnabled(!true);
        jFormattedTextFieldCepCondutor.setEnabled(!true);
        jTextFieldPaisCondutor.setEnabled(!true);
        jComboBoxSexoCondutor.setEnabled(!true);
        jFormattedTextFieldCpfCondutor.setEnabled(!true);
        jButtonSalvarCondutor.setEnabled(!true);
        jButtonNovoCondutor.setEnabled(true);

    }//GEN-LAST:event_jButtonSalvarCondutorActionPerformed

    private void jButtonNovoCondutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCondutorActionPerformed
        // Clicando no botao novo , libera compos para digitação e o botão Salvar.

        jTextFieldNomeCondutor.setEnabled(true);
        jFormattedTextFieldRgCondutor.setEnabled(true);
        jFormattedTextFieldCnhCondutor.setEnabled(true);
        jFormattedTextFieldEmissaoCondutor.setEnabled(true);
        jFormattedTextFieldValidadeCondutor.setEnabled(true);
        jFormattedTextFieldNascCondutor.setEnabled(true);
        jTextFieldCivilCondutor.setEnabled(true);
        jTextFieldCategoriaCondutor.setEnabled(true);
        jFormattedTextFieldTelefone01Condutor.setEnabled(true);
        jFormattedTextFieldTelCelCondutor.setEnabled(true);
        jFormattedTextFieldTelefoneCondutor02.setEnabled(true);
        jTextFieldEnderecoCondutor.setEnabled(true);
        jTextFieldNumeroCondutor.setEnabled(true);
        jTextFieldComplementoCondutor.setEnabled(true);
        jTextFieldBairroCondutor.setEnabled(true);
        jTextFieldCidadeCondutor.setEnabled(true);
        jTextFieldUfCondutor.setEnabled(true);
        jFormattedTextFieldCepCondutor.setEnabled(true);
        jTextFieldPaisCondutor.setEnabled(true);
        jComboBoxSexoCondutor.setEnabled(true);
        jFormattedTextFieldCpfCondutor.setEnabled(true);
        jButtonSalvarCondutor.setEnabled(true);
        jButtonNovoCondutor.setEnabled(false);
        jTextFieldPesquisarCondutor.setEnabled(false);
        jButtonPesquisarCondutor.setEnabled(false);
        jTableCondutor.setEnabled(false);

    }//GEN-LAST:event_jButtonNovoCondutorActionPerformed

    private void jButtonPesquisarCondutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCondutorActionPerformed
       mod.setPesquisar(jTextFieldPesquisarCondutor.getText());// pesquisa pelo campo nome da escola
        BeansCondutor model = DaoCondutor.buscaCondutor(mod);
        // tras do banco e coloca nos campos 
        jTextFieldNomeCondutor.setText(model.getNome());
        jFormattedTextFieldRgCondutor.setText(model.getRg());
        jFormattedTextFieldCnhCondutor.setText(model.getCnh());
        jFormattedTextFieldEmissaoCondutor.setText(model.getEmissaoCnh());
        jFormattedTextFieldValidadeCondutor.setText(model.getValidadeCnh());
        jFormattedTextFieldNascCondutor.setText(model.getNascimento());
        jTextFieldCivilCondutor.setText(model.getCivil());
        jTextFieldCategoriaCondutor.setText(model.getCatHabilitacao());
        jFormattedTextFieldTelefone01Condutor.setText(model.getTelefone01());
        jFormattedTextFieldTelCelCondutor.setText(model.getCelular());
        jFormattedTextFieldTelefoneCondutor02.setText(model.getTelefone02());
        jTextFieldEnderecoCondutor.setText(model.getEndereço());
        jTextFieldNumeroCondutor.setText(model.getNumero() );
        jTextFieldComplementoCondutor.setText(model.getComplemento());
        jTextFieldBairroCondutor.setText(model.getBairro());
        jTextFieldCidadeCondutor.setText(model.getCidade());
        jTextFieldUfCondutor.setText(model.getUf());
        jFormattedTextFieldCepCondutor.setText(model.getCep());
        jTextFieldPaisCondutor.setText(model.getPais());
        jComboBoxSexoCondutor.setSelectedItem(model.getSexo());
        jFormattedTextFieldCpfCondutor.setText(model.getCpf());
        jButtonEditarCondutor.setEnabled(true);
        jButtonExcluirCondutor.setEnabled(true);
        
        
        
    }//GEN-LAST:event_jButtonPesquisarCondutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCondutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCondutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCondutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCondutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCondutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarCondutor;
    private javax.swing.JButton jButtonEditarCondutor;
    private javax.swing.JButton jButtonExcluirCondutor;
    private javax.swing.JButton jButtonNovoCondutor;
    private javax.swing.JButton jButtonPesquisarCondutor;
    private javax.swing.JButton jButtonSalvarCondutor;
    private javax.swing.JComboBox<String> jComboBoxSexoCondutor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCepCondutor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCnhCondutor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfCondutor;
    private javax.swing.JFormattedTextField jFormattedTextFieldEmissaoCondutor;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascCondutor;
    private javax.swing.JFormattedTextField jFormattedTextFieldRgCondutor;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelCelCondutor;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone01Condutor;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneCondutor02;
    private javax.swing.JFormattedTextField jFormattedTextFieldValidadeCondutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneAbas;
    private javax.swing.JTable jTableCondutor;
    private javax.swing.JTextField jTextFieldBairroCondutor;
    private javax.swing.JTextField jTextFieldCategoriaCondutor;
    private javax.swing.JTextField jTextFieldCidadeCondutor;
    private javax.swing.JTextField jTextFieldCivilCondutor;
    private javax.swing.JTextField jTextFieldCodCondutor;
    private javax.swing.JTextField jTextFieldComplementoCondutor;
    private javax.swing.JTextField jTextFieldEnderecoCondutor;
    private javax.swing.JTextField jTextFieldNomeCondutor;
    private javax.swing.JTextField jTextFieldNumeroCondutor;
    private javax.swing.JTextField jTextFieldPaisCondutor;
    private javax.swing.JTextField jTextFieldPesquisarCondutor;
    private javax.swing.JTextField jTextFieldUfCondutor;
    // End of variables declaration//GEN-END:variables
}
